apiVersion: v1
kind: Service
metadata:
  name: http-page-hit
  annotations:
    prometheus.io/scrape: "true"
    #prometheus.io/path: "metrics"
    #prometheus.io/port: "8080"
spec:
  selector:
    app: http-page-hit
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800